# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Device-Velleman-K8055-Fuse
version:      0.2
version_from: lib/Device/Velleman/K8055/Fuse.pm
installdirs:  site
requires:
    IO::File:                      1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
