--- #YAML:1.0
name:                Device-Velleman-K8055-Fuse
version:             0.91
abstract:            ~
license:             ~
author:              
    - Ronan Oger<ronan@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    IO::File:                      1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
